require:
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - '**/Gemfile'
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'db/seeds.rb'
Rails:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
